name: Filter Folders

on:
  #push:
   # branches: [main]

jobs:
  filter_folders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygithub
      - name: Filter folders
        run: |
          python filter_folders.py
