name: Folder List

on:
  workflow_dispatch:

jobs:
  folder_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List folders
        run: |
          echo "Folder Name,Commit Time" > folder_list.csv
          git ls-tree -r --name-only HEAD | while read folder; do
            if [[ $folder =~ ^[a-zA-Z] ]]; then
              commit_time=$(git log -1 --format=%ad --date=unix -- $folder)
              echo "$folder,$commit_time" >> folder_list.csv
              for subfolder in $(git ls-tree -r --name-only HEAD -- $folder); do
                if [[ $subfolder =~ ^[0-9]{14}$ ]]; then
                  echo "$folder/$subfolder,$commit_time" >> folder_list.csv
                fi
              done
            fi
          done

      - name: Upload CSV file
        uses: actions/upload-artifact@v3
        with:
          name: folder_list.csv
          path: folder_list.csv
