name: Folder List

on:
  workflow_dispatch:

jobs:
  folder_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List folders
        run: |
          echo "Folder Name,Commit Time" > folder_list.csv
          # Get all folders in the repo
          git ls-tree -r --name-only HEAD | while read folder; do
            # Check if the folder name is non-numerical
            if [[ $folder =~ ^[a-zA-Z]+$ ]]; then
              commit_time=$(git log -1 --format=%ad --date=unix -- $folder)
              echo "$folder,$commit_time" >> folder_list.csv
            fi
          done

          # Get all subfolders
          git ls-tree -r --name-only HEAD | while read subfolder; do
            # Check if it matches the 14-digit numerical condition
            if [[ $subfolder =~ ^[0-9]{14}$ ]]; then
              parent_folder=$(dirname "$subfolder")
              # Check if the parent folder name is non-numerical
              if [[ $parent_folder =~ ^[a-zA-Z]+$ ]]; then
                commit_time=$(git log -1 --format=%ad --date=unix -- $parent_folder)
                echo "$parent_folder/$subfolder,$commit_time" >> folder_list.csv
              fi
            fi
          done

      - name: Upload CSV file
        uses: actions/upload-artifact@v3
        with:
          name: folder_list.csv
          path: folder_list.csv
